// ==UserScript==
// @name        translate dqmj3.com
// @namespace   translate-dqmj3.com
// @match       https://dqmj3.com/*
// @grant       none
// @version     1.0
// @author      -
// @description translate monster name dqmj3.com
// @updateURL 	https://github.com/pokil/translate-dqmj3.com/raw/master/dqmj3.com.meta.js
// @downloadURL https://github.com/pokil/translate-dqmj3.com/raw/master/dqmj3.com.user.js
// ==/UserScript==


var monsters = {
    "あおだけ童子": "Bamboo Boy",
    "あばれうしどり": "Bullfinch",
    "あらくれチャッピー": "Twilight Chappie",
    "いしにんぎょう": "Dirty Dogu",
    "いたずらもぐら": "Mischievous Mole",
    "いっかくウサギ": "Bunnicorn",
    "うおのりデビル": "Sea Cavalier",
    "うごくせきぞう": "Living Statue",
    "うずしおキング": "Spinchilla",
    "うみうし": "Merlusc",
    "うみぼうず": "Seasludge",
    "えんまのつかい": "Enma's Envoy",
    "おおきづち": "Hammerhood",
    "おおなめくじ": "Maulusc",
    "おにこんぼう": "Night Clubber",
    "おばけきのこ": "Funghoul",
    "おむつっこり": "Nappy Baby",
    "かげのきし": "Dark Skeleton",
    "かっちゅうアリ": "Bulletproof Beatle",
    "かまいたち": "Wind Sickles",
    "がいこつ": "Skeleton",
    "きめんどうし": "Lump Shaman",
    "きりかぶおばけ": "Stump Chump",
    "くさった死体": "Walking Corpse",
    "くろカビこぞう": "Funky Feta",
    "ぐんたいガニ": "Crabid",
    "けいけんち3000": "EXP 3000",
    "けがれの渦": "Mucky Eddy",
    "げんじかぶと": "Mosquitle Beatle",
    "げんじゅつし": "Lump Mage",
    "ごくらくちょう": "Elysium Bird",
    "さつじんエイ": "Murderous Anchor",
    "さまようよろい": "Restless Armour",
    "しびれあんこう": "Mangler",
    "しびれくらげ": "Man-o-war",
    "しましまキャット": "Candy Cat",
    "しりょうのきし": "Skeleton Soldier",
    "しん・りゅうおう": "Lord Draco",
    "じげんりゅう": "Dimensional Dragon",
    "じごくのたまねぎ": "Brimstone Bulb",
    "じごくのよろい": "Infernal Armour",
    "じごくのハサミ": "Crabber Dabber Doo",
    "じめじめバブル": "Dank Slime",
    "せつげんりゅう": "Tundragon",
    "せみもぐら": "Boring Bug",
    "たけやりへい": "Bamboo Soldier",
    "たこまじん": "Devilfish",
    "たつのこナイト": "Aquestrian Gladiator",
    "たまねぎマン": "Loathsome Leek",
    "たんすミミック": "Horrordrobe",
    "だいおうイカ": "King Squid",
    "だいおうキッズ": "Squid kid",
    "だいおうクジラ": "Stale Whale",
    "だいまじん": "Granite Titan",
    "つららスライム": "Slimecicle",
    "てんのもんばん": "Gilded Colossus",
    "とうろうへい": "Lantern Minion",
    "とげこんぼう": "Spiked Clubber",
    "とげジョボー": "Voodoo Doll",
    "とっしんこぞう": "Chariot Chappie",
    "とつげきうお": "Fangfish",
    "どくどくバルーン": "Poison Petey",
    "どくろあらい": "Haardvark",
    "どろどろマントル": "Sulfurous Sammy",
    "どんぐりベビー": "Bulby Baby",
    "なげきの亡霊": "Tortured Soul",
    "なげきムーン": "Mourning Moon",
    "にじくじゃく": "Prism Peacock",
    "ぬかどこスライム": "Shroom Slime",
    "ぬしさま": "Lleviathan",
    "ぬすっとウサギ": "Robber Rabbit",
    "のろいの岩": "Droll Roller",
    "はぐれメタルキング": "Liquid Metal Slime King",
    "はぐれメタル": "Liquid Metal Slime",
    "ばくだんいわ": "Rockbomb",
    "ひくいどり": "Firebird",
    "ひとくいそう": "Carnivine",
    "ひとくい箱": "Cannibox",
    "ふくまねき": "Target Boy",
    "べビル": "Grimlin",
    "ベビル": "Grimlin",
    "ほうおう": "Phoenix",
    "ほねコウモリ": "Skelebat",
    "ほねリーダー": "Swooperior",
    "まいまいテイル": "Snail Tail",
    "まおうのたまご": "Beaster Egg",
    "まかいファイター": "Mandrake Monarch",
    "ましょうぐも": "Demon Cloud",
    "みずたまドラゴン": "Dappled Dragon",
    "みならい神獣": "Fledgling Card",
    "ももいろ三姉妹": "Pink Triplets",
    "ももんじゃ": "Platypunk",
    "やつざきアニマル": "Ferocial",
    "やまたのおろち": "Yamata no Orochi",
    "やみしばり": "Chained Darkhood",
    "ゆめにゅうどう": "Dream Eater",
    "ようかい魚": "Frightbait",
    "りゅうおう": "Dragonlord",
    "りゅうせんし": "Mandrake Marauder",
    "れんごくちょう": "Hybird",
    "れんごくまちょう": "Bird of Terrordise",
    "れんごく天馬": "Tantamount",
    "わたぼう": "Cottney",
    "アイアンクック": "Robo-Robin",
    "アイアンタートル": "Armored Wartoise",
    "アイスゴーレム": "Ice Golem",
    "アイスボンバー": "Icicle Beatle",
    "アカツキショウグン": "Mandrake Master",
    "アカリリス": "S'quarrel",
    "アクバー": "Blackmar",
    "アサシンブラッド": "Bloody Assassin",
    "アスタロト": "Astaroth",
    "アスラゾーマ": "Asura Zoma",
    "アックスドラゴン": "Axesaurus",
    "アックル": "Aquille",
    "アッフェブラック": "Affable Black",
    "アトラス": "Atlas",
    "アニマルゾンビ": "Putrefido",
    "アパデマク": "Apademak",
    "アモデウス": "Amodeus",
    "アルケミストン": "Oinkemist",
    "アルダララ": "Aldarahla",
    "アルミラージ": "Spiked Hare",
    "アンクルホーン": "Moosifer",
    "アークデーモン": "Archdemon",
    "アークバッファロー": "Bulldozer",
    "イエティ": "Powie Yowie",
    "イエローシックル": "Yellow Sickle",
    "イルカちょうちん": "Pumpoise",
    "インキュバス": "Incubus",
    "ウィンデオ": "Windeo",
    "ウパソルジャー": "Upa Soldier",
    "ウパパロン": "Axolhotl",
    "ウルベア魔神兵": "Totem of Urubea",
    "エスターク": "Estark",
    "エビルアングラー": "Dangler",
    "エビルソーサラー": "Mystic Crusader",
    "エビルチクリン": "Bamboo Bully",
    "エビルチャリオット": "Corrupt Carter",
    "エビルホーク": "War Gryphon",
    "エビルワンド": "Wraithwand",
    "エメラルドーン": "Emeraldon",
    "エルダードラゴン": "Elder Dragrove",
    "エレフローバー": "Elepus",
    "エレメングリーン": "Green Glow",
    "エンゼルスライム": "Angel Slime",
    "エンタシスマン": "Prancing Pillar",
    "エンペラン": "Eggsalted Leader",
    "オクトリーチ": "Suckling Ocker",
    "オニオーン": "Ornery Onion",
    "オベルジーヌ": "Übergine",
    "オムド・ロレス": "Rigor Mortex",
    "オリエンタシス": "Copper Column",
    "オークキング": "Orc King",
    "オーク": "Orc",
    "オーシャンボーン": "Pale Whale",
    "カイザードラゴン": "Kaiser Dragon",
    "カシャロット": "Kashalot",
    "カバシラー": "Swarm Troopers",
    "カラーフォンデュ": "Rainbow Fondude",
    "カンダタセブン": "Kandar Viking Force",
    "カンダタレディース": "Kandar Ladies",
    "カンダタ": "Kandar",
    "ガオガイヤ": "Gaogaia",
    "ガチャコッコ": "Clockwork Cuckoo",
    "ガニラス": "Handsome Crab",
    "ガネーシャエビル": "Evil-Ganesh",
    "ガマキャノン": "Mortoad",
    "ガメゴンレジェンド": "Wonder Wyrtle",
    "ガメゴンロード": "Wyrtoise",
    "ガメゴン": "Wyrtle",
    "ガルハート": "Hawkhart",
    "ガルバゴルバ": "Galbagorba",
    "ガルビルス": "Snapped-off",
    "ガルマザード": "Snapped-Almighty",
    "ガルマッゾ": "Dr Snapped",
    "ガルーダ": "Garuda",
    "ガーゴイル": "Gargoyle",
    "ガードマスター": "Guard Master",
    "キメラ": "Chimaera",
    "キャット・リベリオ": "Cat Liberio",
    "キャノンキング": "Blastoad",
    "キャプテンドラゴ": "Sealamander",
    "キャプテン・クロウ": "Captain Crow",
    "キラーアーマー": "Lethal Armour",
    "キラーウェーブ": "Killer Wave",
    "キラークラブ": "King Crab",
    "キラークリムゾン": "Killer Crimson",
    "キラーグース": "Deadly Dodo",
    "キラースコップ": "Mad Mole",
    "キラータイガー": "Striking Sabercat",
    "キラーパンサー": "Great Sabrecat",
    "キラーピッケル": "Maniacal Mole",
    "キラーマシンライト": "Killing Machine Lite",
    "キラーマシン２": "Overkilling Machine",
    "キラーマシン": "Killing Machine",
    "キラーマジンガ": "Überkilling Machine",
    "キラーモス": "Killer Moth",
    "キルバーン": "Kill-Vearn",
    "キングエレファント": "Elephant King",
    "キングスペーディオ": "Wulfspade Ace",
    "キングスライム": "King Slime",
    "キングヒドラ": "King Hydra",
    "キングホイミスライム": "King Healslime",
    "キングモーモン": "King Teeny Sanguini",
    "キングリザード": "Liege Lizard",
    "キングレオ": "Marquis de Léon",
    "キースドラゴン": "Blue Dragon",
    "ギガデーモン": "Pruslas",
    "ギガンテス": "Gigantes",
    "ギガントドラゴン": "Drakulard",
    "ギガントヒルズ": "Drakularge",
    "ギズモ": "Cumaulus",
    "ギャスモン": "Propane Man",
    "ギュメイ将軍": "Goresby-Purrvis",
    "ギーグハンマー": "Hammer Bammer",
    "クインガルハート": "Hawkhart Ace",
    "ククリ": "Krilly",
    "クックルー": "Grudgerigar",
    "クラーゴン": "Tentacular",
    "クロコダイモス": "Darkodile",
    "グラコスエビル": "Gracolyte",
    "グラコス５世": "Gracos V",
    "グラコス": "Gracos",
    "グラブゾンジャック": "Cluboon Ace",
    "グラブゾン": "Cluboon",
    "グランエスターク": "Gran Estark",
    "グランエスターク": "Grand Estark",
    "グランシーザー": "Grancaesar",
    "グランドラゴーン": "Grand Hydra",
    "グリーンシザー": "Green Scissors",
    "グレイトドラゴン": "Great Dragon",
    "グレイトライドン": "Great Ridon",
    "グレイナル": "Greygnarl",
    "グレイブディガー": "Grave Digger",
    "グレムリン": "Gremlin",
    "グレートオーラス": "War-rus",
    "グレートノチョーラＺ": "Great Nochoro Z",
    "グレートペリカン": "Perky Pelican",
    "グール": "Ghoul",
    "ケンタラウス": "Centaurus",
    "ゲマ": "Ladja",
    "ゲルニック将軍": "Hootingham-Gore",
    "ゲルバトロス": "Galbatross",
    "コトブキーノ": "Bamboo Priest",
    "コープスフライ": "Corpsebat",
    "ゴメちゃん": "Gome-chan",
    "ゴルゴンゾーラ": "Gross Gorgonzola",
    "ゴレオン将軍": "Goreham-Hogg",
    "ゴンズ": "Slon",
    "ゴースト": "Ghost",
    "ゴールデンコーン": "Golden Hare",
    "ゴールデンゴーレム": "Balhib",
    "ゴールデンスライム": "Gem Slime",
    "ゴールデントーテム": "Gem Jamboree",
    "ゴールドアクセル": "J3P Axel Gold",
    "ゴールドアクセル": "J3P-Gold Axel",
    "ゴールドウィング": "Gold Wing",
    "ゴールドウィング": "J3P-Gold Wing",
    "ゴールドエンゼル": "Gold Angel Slime",
    "ゴールドオーク": "Orc Chieftain",
    "ゴールドタヌ": "Gold Tanuki",
    "ゴールドノチョーラＺ": "Gold Nochoro Z",
    "ゴールドパール": "Golden Pearl Slime",
    "ゴールドマジンガ": "Mazinger G",
    "ゴールドマリン": "J3P-Gold Marine",
    "ゴールドマン": "Gold Golem",
    "ゴールド1000": "Gold 1000",
    "ゴールド5000": "Gold 5000",
    "ゴーレム": "Golem",
    "サイクロプス": "Cyclops",
    "サイコピサロ": "Psycho Psaro",
    "サイコマスター": "Psycho Crusader",
    "サイレス": "Gryphon",
    "サウルスロード": "Tyrannoceratops",
    "サタンジェネラル": "Loss Leader",
    "サボテンゴールド": "Gold Cactiball",
    "サボテンボール": "Cactiball",
    "サンダーシャウト": "Booming Thunder",
    "サンチョゼロ": "Sancho Zero",
    "サンチョ": "Sancho",
    "サンドウェーブ": "Sand Wave",
    "サージタウス": "Sagittar",
    "シャイニング": "Spitnik",
    "シャドウパンサー": "Dark Sabrecat",
    "シャドウベビー": "Dark Sabercub",
    "シャドーノーブル": "Noble Shadow",
    "シャドーノーブル": "Shadow Noble",
    "シャドー": "Shadow",
    "シャンタク": "Shantak",
    "シャークマンタ": "Ultraviolent Ray",
    "シュバルツシュルト": "Blight Armour",
    "シュプリンガー": "Mandrake Marshal",
    "シルバリヌス": "Holy Baron",
    "シルバーデビル": "Silvapithecus",
    "シルバー": "Silver",
    "シーザーレインボー": "Rainbow Scissors",
    "シーデーモン": "Fangler",
    "シードラゴンズ": "Quayhorse",
    "シーメーダ": "See Urchin",
    "シーライオン": "Maulrus",
    "ジェノシドー": "Genoshidoh",
    "ジェリーマン": "Jellyman",
    "ジャハガロス": "Juggerwroth",
    "ジャミラス": "Jamirus",
    "ジャミ": "Kon",
    "スカイドラゴン": "Sky Dragon",
    "スカルガルー": "Guaardvark",
    "スカルゴン": "Skelegon",
    "スカルドン": "Drakenstein",
    "スターキメラ": "Cosmic Chimaera",
    "ストーンマン": "Stone Golem",
    "スノードラゴン": "Snow Dragon",
    "スノーモン": "Snowy Sanguini",
    "スパイクヘッド": "Spiked 'Doo",
    "スピンサタン": "Dark Star",
    "スペシャルプレゼント": "Special Present",
    "スペディオ": "Wulfspade",
    "スマイルリザード": "Lively Lizard",
    "スマイルロック": "Grinade",
    "スライダーガール": "Slamen Rider Girl",
    "スライダーキッズ": "Slamen Tykes",
    "スライダークロボ": "Dark Robo-Slime",
    "スライダークロボ": "Slamen Robo",
    "スライダーヒーロー": "Slamen Rider",
    "スライムつむり": "Shell Slime",
    "スライムエンペラー": "Emperor Slime",
    "スライムゴールド": "Gold Slime",
    "スライムタワー": "Slime Stack",
    "スライムナイト": "Slime Knight",
    "スライムファミリー": "Slime Family Reunion",
    "スライムブレス": "Dragon Slime",
    "スライムベス": "She-Slime",
    "スライムベホマズン": "King Cureslime",
    "スライムマデュラ": "Darkonium Slime",
    "スライム系": "Slime",
    "スライム": "Slime",
    "スラキャンサー": "Slime Cancer",
    "スーパーキラーマシン": "Trauminator",
    "ズッキーニャ": "Cruelcumber",
    "セルゲイナス": "Bilhaw",
    "セージももんじゃ": "Platypunk Scholar",
    "ソードフライヤー": "Goregoyle",
    "ゾンビ系": "Zombie",
    "ゾーマズデビル": "Zoma's Little Devil",
    "タイプG": "Type G",
    "タホドラキー": "Drackmage",
    "タマゴロン": "Bad Egg",
    "ダグジャガルマ": "Jormungandros",
    "ダゴン": "Octophant",
    "ダックスビル": "Splatypunk",
    "ダッシュラン": "Drag Racer",
    "ダブルイーター": "Elemental Pair",
    "ダブルバングル": "Double Hitter",
    "ダンスニードル": "Fandangow",
    "ダークトロル": "Terror Troll",
    "ダークドリアード": "Dark Dryad",
    "ダークドレアム": "Nokturnus",
    "ダークネビュラス": "Dark Nebula",
    "ダークプラネット": "Gloomy Globe",
    "ダークマンモス": "Dark Eyelephant",
    "ダークモーモン": "Dark Sanguini",
    "ダースガルマ": "Snapped-Dragon",
    "ダースドラゴン": "Red Dragon",
    "ダーティラビッツ": "Dirty Bunny",
    "チウ": "Chiu",
    "チャームバット": "Charmbat",
    "ツイストーチ": "Colonnade of Combustion",
    "ティコ": "Tiko",
    "テラノライナー": "Tyranoliner",
    "テンタクルス": "Squidzilla",
    "ディアノーグエース": "Diamagon Ace",
    "ディアノーグ": "Diamagon",
    "ディープバイター": "Plated Goretoise",
    "デザートゴースト": "Sweaty Yeti",
    "デザートタンク": "Expload",
    "デスカイザー": "Master Moosifer",
    "デスジャッカル": "Rottenweiler",
    "デススタッフ": "Dreadstaff",
    "デスバーン": "Deathvyrn",
    "デスパロット": "Paralakeet",
    "デスピサロ": "Psaro the Manslayer",
    "デスファレーナ": "Giant Moth",
    "デスプリースト": "Wight Priest",
    "デスマエストロ": "Malicious Maestro",
    "デビルパピヨン": "Devilmoth",
    "デビルプラント": "Venus Guytrap",
    "デビルロード": "Batmandrill",
    "デモンスペーディオ": "Ace of Spades",
    "デモンスペーディオ": "Demon Spade",
    "デュラン": "Dhuran",
    "デンタザウルス": "Tortoceratops",
    "デンデン竜": "Jargon",
    "デーモンキング": "Demon Overlord",
    "トドマン": "Tuskateer",
    "トマホーガー": "Tomahawk Rex",
    "トリカトラプス": "Trikaceratops",
    "トロルバッコス": "Trollciopath",
    "トロルボンバー": "Stout Troll",
    "トロル": "Troll",
    "トワイライトメア": "Twilightmare",
    "トンネラー": "Tunneler",
    "トンブレロ": "Swinebrero",
    "トードー": "Toto",
    "トーポ": "Topo",
    "ドラキーマ": "Drackyma",
    "ドラキー": "Dracky",
    "ドラゴスライム": "Drake Slime",
    "ドラゴメタル": "Metal Drake Slime",
    "ドラゴンガイア": "Gaia Dragon",
    "ドラゴンキッズ": "Small Fry",
    "ドラゴンゾンビ": "Dragon Zombie",
    "ドラゴンデストロイ": "Battle Axesaurus",
    "ドラゴンバゲージ": "Dragurn",
    "ドラゴン・ウー": "Drakulord",
    "ドラゴン系": "Dragon",
    "ドラゴン": "Green Dragon",
    "ドルイド": "Lump Wizard",
    "ドルマゲス": "Dhoulmagus",
    "ドロヌーバ": "Mudraker",
    "ドン・モグーラ": "Don Mole",
    "ドーク": "Darck",
    "ナイトメーア": "Nightmare",
    "ナウマンボーグ": "Naumannborg",
    "ナスビナーラ": "Woebergine",
    "ニジゴロン": "L'arc-en-Shell",
    "ニードルフィン": "Needlephin",
    "ニードルマン": "Needleman",
    "ネクロマンサー": "Necromancer",
    "ハーゴン": "Hargon",
    "ハートナイト": "Knight of Hearts",
    "バアルゼブブ": "Ba'al Zebub",
    "バザックス": "Terrorceratops",
    "バズズ": "Pazuzu",
    "バトルレックス": "Hackasaurus",
    "バブリン": "Zepling",
    "バブルスライム": "Bubble Slime",
    "バラクーダ": "Barracuda",
    "バラモスエビル": "Baramos Evil",
    "バラモスゾンビ": "Bones of Baramos",
    "バラモス": "Baramos",
    "バリイドドッグ": "Bullmustiff",
    "バルザック": "Baalzack",
    "バルボロス": "Barbarus",
    "バロンナイト": "Baron Knight",
    "バーディ": "Birdie",
    "パオーム": "Eyevory Tusk-Tusk",
    "パンドラチェスト": "Pandora's Dresser",
    "パンドラボックス": "Pandora's Box",
    "パールスライム": "Pearl Slime",
    "ヒヒュドラード": "Baboodread",
    "ヒートギズモ": "Hell Niño",
    "ビッグスロース": "Sasquash",
    "ビッグハット": "Big Hat",
    "ビッグファング": "Crocodog",
    "ピッキー": "Bludgerigar",
    "ピッグマリオン": "Pigmalion",
    "ピラニアン": "Piranian",
    "ピンクモーモン": "Pink Sanguini",
    "ファイアボール": "Fabricated Phoenix",
    "ファイナルウェポン": "Final Weapon",
    "ファイナルウェポン": "Ultimate Weapon",
    "ファンキードラゴ": "Sillimander",
    "フィッシュライダー": "Marine Knight",
    "フォレストドラゴ": "Dragrove",
    "フォロボス": "Tyrannosaurus Wrecks",
    "フォンデュ": "Fondude",
    "フライングダック": "Mad Mallard",
    "フレイシャ": "Freshia",
    "フレイム": "Dancing Flame",
    "フロストギズモ": "Freezing Fog",
    "ブオーン": "Bjørn the Behemoose",
    "ブラウニー": "Brownie",
    "ブラス": "Brash",
    "ブラックゴイル": "Black Goyle",
    "ブラックゴーレム": "Coalem",
    "ブラックタヌー": "Black Tanuki",
    "ブラックチャック": "Special Brownie",
    "ブラックドラゴン": "Black Dragon",
    "ブラックベジター": "Black Veggie",
    "ブラックマンティス": "Black Mantis",
    "ブラックモス": "Dark Moth",
    "ブラッドハンド": "Bloody Hand",
    "ブラバニクイーン": "Queenly Hare",
    "ブリザード": "Frostburn",
    "ブルホーク": "Buffalo Wing",
    "ブルーミンクス": "Blue Minx",
    "ブレイク系": "Boss",
    "ブースカ": "Pudgedevil",
    "プオーン": "Rebjørn",
    "プチアーノン": "Khalamari Kid",
    "プチターク": "Starkers",
    "プチットⅠ・Ⅱ": "Chibi One-Twos",
    "プチットⅢ": "Chibi Threes",
    "プチットⅣ": "Chibi Fours",
    "プチットⅧ": "Chibi Eights",
    "プチットガールズ": "Chibi Heroines",
    "プチット族": "Conklave",
    "プヨンターゲット": "Healium Balloon",
    "プラチナキング": "Platinum King",
    "プラチナノチョーラＺ": "Platinum Nochoro Z",
    "プリズニャン": "Jailcat",
    "プリーストナイト": "Masked Crusader",
    "プレミアムスライム": "Premium Slime",
    "プロメテウス": "Prometheus",
    "ヘルカッチャ": "Hell Catcher",
    "ヘルクラウド": "Stormsgate Citadel",
    "ヘルクラッシャー": "Hell Gladiator",
    "ヘルコンダクター": "Nightmare Conductor",
    "ヘルコンドル": "Hades Condor",
    "ヘルゴースト": "Spitegeist",
    "ヘルジュラシック": "Jurrassic Hellion",
    "ヘルバトラー": "Barbatos",
    "ヘルプラネット": "Solaris",
    "ベスキング": "Queen Slime",
    "ベヒードス": "Drakulurch",
    "ベビンゴサタン": "Bebingo Satan",
    "ベビーサタン": "Imp",
    "ベビータイガー": "Striking Sabercub",
    "ベビーニュート": "Minewt",
    "ベビーパンサー": "Great Sabercub",
    "ベホマスライム": "Cureslime",
    "ベリアル": "Belial",
    "ベロニャーゴ": "Terror Tabby",
    "ホイップゴースト": "Whipped Scream",
    "ホイミスライム": "Heal Slime",
    "ホロゴースト": "Hologhost",
    "ホークブリザード": "Snowbird",
    "ホークマン": "Hawk Man",
    "ボストロール": "Boss Troll",
    "ボボンガー": "Bongobrute",
    "ボーンバット": "Skullbat",
    "ボーンフィッシュ": "Bonefish",
    "ポイズントリル": "Spoilt Scream",
    "ポグフィッシュ": "Wild Boarfish",
    "ポセイドン": "Poseidon",
    "ポムポムボム": "Discombombulator",
    "ポンポコだぬき": "Ram-tam Tanuki",
    "マグマロン": "Magman",
    "マザーオクト": "Mother Ocker",
    "マジカルハット": "Hog Hat",
    "マスタードラゴン": "Master Dragon",
    "マタンゴ": "Morphean Mushroom",
    "マッシュスライム": "Truffle Slime",
    "マッドウェーブ": "Mad Wave",
    "マッドスミス": "Mud Smith",
    "マッドファルコン": "Terrorhawk",
    "マドハンド": "Muddy Hand",
    "マドルーパー": "Bogman",
    "マポレーナ": "Genie Sanguini",
    "マリンスライム": "Seaslime",
    "マリンフェアリー": "See Sprite",
    "マンドレイク": "Mandragore",
    "マージマタンゴ": "Mushroom Mage",
    "マーズフェイス": "Mars Mug",
    "マーブルン": "Prism Puss",
    "ミステリピラー": "Cavorting Column",
    "ミステリードール": "Cavorting Column",
    "ミストバーン": "Myst-Vearn",
    "ミニデーモン": "Minidemon",
    "ミミック": "Mimic",
    "ムドー": "Murdaw",
    "ムド―": "Murdaw",
    "ムーンキメラ": "Lunar Chimaera",
    "メイジももんじゃ": "Crack-Billed Platypunk",
    "メイジキメラ": "Hocus Chimaera",
    "メイジドラキー": "Drackolyte",
    "メカバーン": "Mechan-o-wyrm",
    "メガザルロック": "Bomboulder",
    "メタッピー": "Mecha-Mynah",
    "メタルエンゼル": "Metal Angel Slime",
    "メタルキング": "Metal King Slime",
    "メタルゴッデス": "Metal Goddess",
    "メタルスライム": "Metal Slime",
    "メタルトリュフ": "Metal Truffle",
    "メタルドラゴン": "Metal Dragon",
    "メタルハンター": "Hunter Mech",
    "メタルパール": "Metal Pearl Slime",
    "メタルブラザーズ": "Metal Medley",
    "メタルホイミン": "Metal Healie",
    "メタルライダー": "Metal Slime Knight",
    "メトロゴースト": "Fightgeist",
    "メラリザード": "Frizzard",
    "メランザーナ": "Awebergine",
    "メーダボード": "Metabode",
    "モコフル": "Fluffy Puffy",
    "モテモテ": "Yellow Bellow",
    "モーモン": "Teeny Sanguini",
    "ユニコーン": "Ewwnicorn",
    "ラプソーン": "Rhapthorne",
    "ラマダ": "Queen Ferz",
    "ラーミア": "Ramia",
    "リザードマン": "Mandrake Major",
    "リトルライバーン": "Little Burner",
    "リビングデッド": "Corpse Corporal",
    "リュウイーソー": "Li'l Whizzer",
    "ルバンカ": "Rubanka",
    "レイギガース": "Gigas Ray",
    "レイギガ―ス": "Gigas Ray",
    "レオパルド": "Sir Leopold",
    "レオン・ビュブロ": "Leon Byblos",
    "レジアクセル": "J3-Rebel Axel",
    "レジウィング": "J3-Rebel Wing",
    "レジェンドホース": "Godsteed",
    "レジェンドホーン": "Mythsteed",
    "レジマリン": "J3-Rebel Marine",
    "レッドサイクロン": "Red Cyclone",
    "レッドプリン": "Eyes Scream",
    "レティス": "Empyrea",
    "ロイヤルミミック": "Royal Armoir",
    "ローズバトラー": "Gripevine",
    "ロードコープス": "Wight Emperor",
    "ワイトキング": "Wight King",
    "ワニバーン": "Heligator",
    "ワルぼう": "Rottney",
    "ワンダーエッグ": "Rotten Egg",
    "ヴォルカドラゴン": "Volcanic Dragrove",
    "伐採マシン": "Robo-Reaper",
    "冥獣王ネルゲル": "Hades Nelgel",
    "凶おおみみず": "Δ Landwurm",
    "凶おおみみず": "Broken Wiggly",
    "凶ぐんたいガニ": "Δ Crabid",
    "凶じごくのハサミ": "Δ Crabber Dabber Doo",
    "凶だいおうイカ": "Δ King Squid",
    "凶とげジョボー": "Δ Voodoo Doll",
    "凶なげきムーン": "Δ Mourning Moon",
    "凶にじくじゃく": "Δ Prism Peacock",
    "凶ぬしさま": "Δ Lleviathan",
    "凶アトラス": "Δ Atlas",
    "凶アークデーモン": "Δ Archdemon",
    "凶エスターク": "Δ Estark",
    "凶エルダードラゴン": "Δ Elder Dragrove",
    "凶キメラ": "Δ Chimaera",
    "凶キラークラブ": "Δ King Crab",
    "凶キングリザード": "Δ Liege Lizard",
    "凶ギガンテス": "Δ Gigantes",
    "凶クラーゴン": "Δ Tentacular",
    "凶グレートオーラス": "Δ War-rus",
    "凶シーライオン": "Δ Maulrus",
    "凶スカルゴン": "Δ Skelegon",
    "凶スターキメラ": "Δ Cosmic Chimaera",
    "凶スパイクヘッド": "Δ Spiked 'Doo",
    "凶スライムベス": "Δ She-Slime",
    "凶スライム": "Δ Slime",
    "凶ダークプラネット": "Δ Gloomy Globe",
    "凶トドマン": "Δ Tuskateer",
    "凶ドラゴンガイア": "Δ Gaia Dragon",
    "凶ドラゴンゾンビ": "Δ Dragon Zombie",
    "凶フォレストドラゴ": "Δ Dragrove",
    "凶マッドファルコン": "Δ Terrorhawk",
    "凶マーズフェイス": "Δ Mars Mug",
    "凶メイジキメラ": "Δ Hocus Chimaera",
    "凶メカバーン": "Δ Mechan-o-wyrm",
    "凶メタルスライム": "Δ Metal Slime",
    "凶メタルドラゴン": "Δ Metal Dragon",
    "凶レオン・ビュブロ": "Δ Leon Byblos",
    "凶ヴォルカドラゴン": "Δ Volcanic Dragrove",
    "凶鳥フレス": "Δ Hraesvelgr",
    "創造神マデサゴーラ": "Madesgora",
    "勇車スラリンガル": "Schleiman Tank",
    "名もなき闇の王": "He Who Bears no Name",
    "呪術師マリーン": "Shaman Marline",
    "堕天使エルギオス": "Corvus the Fallen",
    "大地の竜バウギア": "Geodraco Baugaia",
    "大怨霊マアモン": "Mammon",
    "大食王ボーショック": "Boshock",
    "大魔王ゾーマ": "Archfiend Zoma",
    "大魔王デスタムーア": "Demonlord Mortamor",
    "大魔王バーン": "Great King Vearn",
    "大魔王マデュラージャ": "Madullajah Djinn",
    "天魔クァバルナ": "Kabalna the Divine",
    "女帝フレイシャ": "Queen Freshia",
    "妖剣士オーレン": "Calamity Blade Oren",
    "妖魔ジュリアンテ": "Mystic Juliante",
    "妖魔将ゲジュラ": "Giestlord Gejura",
    "守護者ラズバーン": "Guardian Lazuvann",
    "密林の守人": "Jungle Guardian",
    "少年レオソード": "Leokid",
    "幻魔将ファズマ": "Illusionist Fazma",
    "強奪王ブンドルド": "Bundold",
    "怪力軍曹イボイノス": "Hammibal",
    "怪獣プスゴン": "Pusugon the Monsterous",
    "怪蟲アラグネ": "Arachnida the Enigma",
    "悪魔ザイガス": "Zaigas the Fiend",
    "悪魔系": "Devil",
    "悪魔長ジウギス": "Ziggy the Wicked",
    "戦帝アックル": "Deuce Arqule",
    "拷問王イッタブル": "Itaburu",
    "暗黒の魔人": "Ruin",
    "暗黒大樹の番人": "Darkwood Spirit",
    "暗黒神ラプソーン": "Dark God Rhapthorne",
    "暗黒神ラプソーン": "Rhapthorne",
    "暴君バサグランデ": "Tyrant Basagrande",
    "月夜の将": "Moonlight Shogun",
    "村人A": "Villiger A",
    "死神きぞく": "Bone Baron",
    "死神スライダーク": "Slamen Dark, the Reaper",
    "水竜ギルギッシュ": "Deepdraco Gilgeesh",
    "海のまもりガメ": "Ironclad Wartoise",
    "海の神ワダツミ": "Wadatsumi",
    "深海の守護者": "Defender of the Depths",
    "物質系": "Material",
    "狡猾王アーザムーク": "Azamook",
    "獣魔将ガルレイ": "Phantom Galray",
    "皇帝ウィンディオ": "King Windeo",
    "真・災厄の王": "Disasterking",
    "真・魔王ザラーム": "Fractos Unfettered",
    "石炭つむり": "Coalslime",
    "砂塵の幻馬": "Phantomount",
    "破壊神シドー": "Malroth the Ruinbringer",
    "破壊神シドー": "Malroth",
    "破戒王ベルムド": "Belmud the Destroyer",
    "神さま": "God",
    "神獣界の守り竜": "Incarnus Guardian",
    "神獣界の番人": "Incarnus Gatekeeper",
    "神竜": "Shen Long",
    "神馬アルシオン": "Halcyon the Godsteed",
    "神鳥レティス": "Great Empyrea",
    "空の神ホアカリ": "Hoakari",
    "竜王": "Dragonlord",
    "竜神王": "Dragovian Lord",
    "管理端末Q484": "Master CPU Q484",
    "義帝ガオガイヤ": "Jack Gaogaia",
    "聖竜ミラクレア": "Miraclare",
    "聖銀のどくろあらい": "Silver Haardvark",
    "自然系": "Nature",
    "舞踏魔プレシアンナ": "Dancer Pleshauna",
    "若葉の精霊": "Leaf Sprite",
    "覚醒プスゴン": "Pusugon Awakened",
    "豪魔将ブレンダ": "Devil Dog Brenda",
    "豪魔将ベリンダ": "Devil Dog Belinda",
    "赤飛竜": "Crimson Wyrm",
    "軍神トガミヒメ": "Princess Togami",
    "邪獣ヒヒュルデ": "Beastly Baboorude",
    "邪眼皇帝アウルート": "Fowleye",
    "長老ピピット": "Grandpa Pipit",
    "闇の王ヴラート": "Dark Lord Valaat",
    "闇竜シャムダ": "Shadroth",
    "闘神レオソード": "Leonyx",
    "陸の神ヤチホコ": "Attihocc",
    "青天竜バルケロス": "Valkeros of the Horizons",
    "青飛竜": "Azure Wyrm",
    "鬼眼王バーン": "Vearn, the Beholder",
    "魔人ゼクセン": "Zexen the Devil",
    "魔人リンジャーラ": "Rinjara the Fiend",
    "魔元帥ゼルドラド": "Zeldorado",
    "魔剣士ピサロ": "Psaro of the Demon Clan",
    "魔剣神レパルド": "Excalipurr",
    "魔勇者アンルシア": "Dark Hero Anlucia",
    "魔女グレイツェル": "Enchantress Gretel",
    "魔戦士ルギウス": "Rugius",
    "魔戦士ヴェーラ": "Vera",
    "魔戦神ゼメルギアス": "Zemelgias",
    "魔戦神ゼメルギアス": "Zemelgius",
    "魔獣系": "Beast",
    "魔王の使い": "Demon-at-arms",
    "魔王オムド・レクス": "Timelord Omega Rolex",
    "魔王オルゴ・デミーラ": "Demonking Orgodemir",
    "魔王オルゴ・デミーラ": "Orgodemir",
    "魔王ミルドラース": "Grandmaster Nimzo",
    "魔王軍の残党": "Insurgent Demon",
    "魔界神マデュラーシャ": "Madullajah Marid",
    "魔軍師イッド": "Tactician Iddo",
    "黄飛竜": "Gilded Wyrm",
    "黒き花婿": "Doom Groom",
    "黒竜丸": "Equinox",
    "黒飛竜": "Black Wyrm",
    "黒飛竜": "Equinox",
    "？？？系": "???",
    "ＪＥＳＴＥＲ": "Jester",
    "ＪＯＫＥＲ": "Wildcard",
    "ＷＯＲＬＤ": "Royal Flush",


};


var fam = {
    "悪魔": "Demon",
    "ゾンビ": "Undead",
    "物質": "Material",
    "魔獣": "Beast",
    "ドラゴン": "Dragon",
    "スライム": "Slime",
    "自然": "Nature",
    "ブレイク": "Break"
}
var header = {
    "モンスター名": "Monster Name",
    "種類":"Family",
    "枠":"Size",
    "攻":"ATK",
    "守":"DEF",
    "早":"AGI",
    "賢":"INT",
    "スカウト":"Scouting",
    "配合":"Synth",
}
var loc = {
    "ドローン": "Drone",
    "メタルエリア": "Pedal to the Metal",
    "ワールドマップ": "World Map",
    "光あふれる地": "Gold Rush",
    "凍骨の氷原": "Grim Tundra",
    "崩落都市": "Fallen City",
    "歓楽の霊道": "Spirit Road",
    "焦熱の火山": "Fiery Volcano",
    "神獣界": "Incarnus Realm",
    "静寂の草原": "Silent Meadows",
    "魔王城": "Madullaj Mahal",
    "魔界": "Demon Realm",
    "魔界": "Spirit World",
    "黒鉄の監獄塔": "Darkiron Bastille",
    "インターネット通信": "Wi-Fi Square",
    "マスターズロード": "Masters Road",
    "古文書": "Scrolls",
    "時空の裂け目": "Space-Time Rifts",
    "神獣石": "Incarnus Stone",
    "崩落都市、メタルエリア": "Fallen City, Pedal to the Metal",
    "ちいさなメダル景品": "Mini Medal Prize",
    "勝ち抜きバトル": "Winning Battle",
    "異世界の魔王": "Overlord",
    "時空の裂け目のマスター": "Another Monster Master",
}

function replacer(input, dic, remove) {
    var el = $(input);
    var text = el.text().trim();
    if (remove) {
        text = text.replace(remove, '');
    }
    var en = dic[text];
    if (en) {
        el.contents().filter(function() {
            return this.nodeType == 3
        }).each(function() {
            this.textContent = this.textContent.replace(text, en);
        });
    }
}

$('.table1').find('tbody>tr').each(function(index) {
    if ($(this).hasClass("t1")) {
        $(this).find('th').each(function(index) {
            replacer(this, header);
        });
    }
    $(this).find('td').each(function(index) {
        if (index == 1) {
            replacer($(this).find('a'), monsters);
        } else if (index == 3) {
            replacer(this, fam);
        } else if (index == 10) {
            replacer($(this).find('a'), loc);
        }
    });
});

$('h1').each(function(index) {
    replacer(this, monsters, "配合");
});

$('pre>a').each(function(index) {
    replacer(this, monsters);
});

